#!/usr/bin/env bash

UPDATE_SYSTEM=true
ALLOW_INSTALL_PARU=true

INSTALL_BASE=true
INSTALL_ZSH=true
INSTALL_WEZTERM=true
INSTALL_NVM_NODE=true
INSTALL_PYTHON=true
INSTALL_DOCKER=true
INSTALL_VSCODE=true
INSTALL_GITHUB_CLI=true

INSTALL_FLATPAK=true
INSTALL_BRAVE=true
INSTALL_TELEGRAM=true
INSTALL_LUTRIS=true
INSTALL_STEAM=true
INSTALL_POSTMAN=true
INSTALL_THUNDERBIRD=true

INSTALL_RCLONE=true
INSTALL_SYNCTHING=true
INSTALL_SOLAAR=true
INSTALL_INPUT_REMAPPER=true
INSTALL_ESPANSO=true
INSTALL_VIRTUALIZATION=true
INSTALL_LENOVO_LEGION_LINUX=true
INSTALL_CODEX=false
INSTALL_OPENSSH_SERVER=true
ENABLE_OPENSSH_SERVER=true

INSTALL_BITWARDEN_CLI=true
INSTALL_BITWARDEN_DESKTOP=true
RESTORE_BITWARDEN_SECRETS=true
BITWARDEN_SECRETS_REQUIRED=false
BITWARDEN_OVERWRITE_EXISTING_SECRETS=false
RESTORE_RCLONE_FROM_BITWARDEN=true
RESTORE_SYNCTHING_FROM_BITWARDEN=true
SYNCTHING_RECOVERY_ALLOW_PATHS_OUTSIDE_HOME=false
SYNCTHING_RECOVERY_ALLOW_NONEMPTY_NEW_FOLDERS=false
SYNCTHING_RECOVERY_WAIT_SECONDS=30
BITWARDEN_CLI_INSTALL_METHOD="auto"
# Native fallback is pinned; verify official release metadata before updating.
BITWARDEN_CLI_VERSION="2026.9.0"

ESPANSO_BACKEND="auto"
WEZTERM_CONFIG_REPO="https://github.com/mont2y/wezterm-config.git"
WEZTERM_CONFIG_BRANCH="main"
NVM_VERSION="v0.40.7"
